(function () {
  "use strict";
  const U = () => TDZUtils;
  function currentUser() { return TDZAuth.getUser(); }
  function alertsKey() { const user = currentUser(); return user ? `tenderdz_alerts_${user.email}` : "tenderdz_alerts_visitor"; }
  function getAlerts() { try { return JSON.parse(localStorage.getItem(alertsKey()) || "[]"); } catch (error) { return []; } }
  function saveAlerts(alerts) { localStorage.setItem(alertsKey(), JSON.stringify(alerts)); }
  function calculateAlertResults(alert) {
    const keywords = U().normalize(alert.keywords).split(",").filter(Boolean);
    return TDZTenders.published().filter((tender) => {
      if (alert.category && tender.category !== alert.category) return false;
      if (alert.wilaya && tender.wilaya !== alert.wilaya) return false;
      const content = U().normalize([tender.title, tender.description, tender.requirements, tender.organization].join(" "));
      return !keywords.length || keywords.some((word) => content.includes(word.trim()));
    }).length;
  }
  function dashboardMarkup() {
    const tenders = TDZTenders.published();
    const profile = U().getProfile(); const matches = tenders.filter((tender) => U().matchScore(tender, profile) > 0); const near = tenders.filter((tender) => { const day = U().dayDiff(tender.deadline); return day >= 0 && day <= 7; }).sort((a, b) => a.deadline.localeCompare(b.deadline));
    const recent = [...tenders].sort((a, b) => b.publicationDate.localeCompare(a.publicationDate)).slice(0, 5);
    return `<div class="app-title-row"><div><h2>Bonjour, ${U().escapeHTML(currentUser().name.split(" ")[0])}</h2><p>Voici ce qui mérite votre attention aujourd'hui.</p></div><a class="btn btn-primary" href="${U().pagePath("tenders")}">⌕ Explorer les appels</a></div>
      <div class="stats-grid"><article class="stat-card"><span>Nouveaux appels d'offres</span><strong>${tenders.filter((tender) => U().dayDiff(tender.publicationDate) >= -7).length}</strong><small>publiés cette semaine</small></article><article class="stat-card"><span>Correspondances</span><strong>${matches.length}</strong><small>${profile.keywords ? "selon votre profil" : "complétez votre profil"}</small></article><article class="stat-card"><span>Mes favoris</span><strong>${TDZFavorites.list().length}</strong><small class="neutral">opportunités sauvegardées</small></article><article class="stat-card"><span>Deadlines proches</span><strong>${near.length}</strong><small>dans les 7 prochains jours</small></article></div>
      <div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Appels d'offres récents</h2><a href="${U().pagePath("tenders")}">Tout voir →</a></div>${recent.map((tender) => dashboardTender(tender, profile)).join("")}</section><section class="panel"><div class="panel-heading"><h2>Deadlines imminentes</h2><a href="${U().pagePath("tenders")}">Voir les appels →</a></div><div class="deadline-list">${near.slice(0, 5).map(deadlineItem).join("") || `<p style="margin:0;color:var(--muted);font-size:13px">Aucune deadline dans les 7 prochains jours.</p>`}</div></section></div>`;
  }
  function dashboardTender(tender, profile) { const score = U().matchScore(tender, profile); return `<article class="dashboard-tender"><div><h3><a href="${TDZUtils.pagePath("tender")}?id=${encodeURIComponent(tender.id)}">${U().escapeHTML(tender.title)}</a></h3><p>${U().escapeHTML(tender.organization)} · ${U().escapeHTML(tender.wilaya)}</p></div>${score ? `<span class="match">${score}% match</span>` : TDZTenders.getStatusBadge(tender)}</article>`; }
  function deadlineItem(tender) { const deadline = U().deadlineInfo(tender.deadline); return `<article class="deadline-item"><span class="deadline-date">${U().parseDate(tender.deadline).getDate()}<small>${U().parseDate(tender.deadline).toLocaleDateString("fr-DZ", { month: "short" }).replace(".", "")}</small></span><div><h3><a href="${U().pagePath("tender")}?id=${encodeURIComponent(tender.id)}">${U().escapeHTML(tender.title)}</a></h3><p>${U().escapeHTML(tender.organization)}</p></div><span class="badge ${deadline.className}">${deadline.label}</span></article>`; }
  function favoritesMarkup() { const ids = TDZFavorites.list(); const tenders = ids.map((id) => TDZTenders.find(id)).filter(Boolean); return `<div class="app-title-row"><div><h2>Mes favoris</h2><p>Vos appels d'offres sauvegardés, à suivre avant leurs dates limites.</p></div><a class="btn btn-outline" href="${U().pagePath("tenders")}">⌕ Explorer</a></div><div id="favorite-results" class="tender-list"></div>`; }
  function renderFavorites() { const root = document.getElementById("app-page-content"); root.innerHTML = favoritesMarkup(); TDZTenders.renderCards(TDZFavorites.list().map((id) => TDZTenders.find(id)).filter(Boolean), document.getElementById("favorite-results"), { emptyTitle: "Votre liste de favoris est vide", emptyText: "Sauvegardez les appels importants afin de les retrouver ici.", emptyAction: `<a class="btn btn-primary" href="${U().pagePath("tenders")}">Explorer les appels d'offres</a>` }); }
  function profileMarkup() { const profile = U().getProfile(); return `<div class="app-title-row"><div><h2>Mon profil de veille</h2><p>Vos informations servent au matching local du prototype.</p></div></div><div class="settings-layout"><section class="settings-card card"><h2>Informations de l'entreprise</h2><p>Ces critères permettront plus tard de vous proposer des opportunités adaptées.</p><form id="profile-form" class="form-grid"><div class="form-group"><label for="profile-company">Nom de l'entreprise</label><input id="profile-company" name="company" value="${U().escapeHTML(profile.company)}" placeholder="Ex. ABC Informatique"></div><div class="form-group"><label for="profile-sector">Secteur d'activité</label><input id="profile-sector" name="sector" value="${U().escapeHTML(profile.sector)}" placeholder="Ex. Informatique"></div><div class="form-group"><label for="profile-wilaya">Wilaya</label><select id="profile-wilaya" name="wilaya"><option value="">Sélectionner une wilaya</option>${TDZData.wilayas.map((item) => `<option ${profile.wilaya === item ? "selected" : ""}>${U().escapeHTML(item)}</option>`).join("")}</select></div><div class="form-group"><label for="profile-keywords">Mots-clés recherchés</label><input id="profile-keywords" name="keywords" value="${U().escapeHTML(profile.keywords)}" placeholder="ordinateurs, serveurs, réseau"></div><div class="form-group span-2"><label for="profile-description">Description de l'activité</label><textarea id="profile-description" name="description" placeholder="Présentez brièvement votre activité...">${U().escapeHTML(profile.description)}</textarea></div><div class="span-2"><button class="btn btn-primary" type="submit">Enregistrer mon profil</button></div></form></section><aside class="side-tip"><h2>Comment fonctionne le matching ?</h2><p>Le MVP compare vos mots-clés avec le titre, la description, la catégorie et les exigences de chaque appel. Ce calcul local sera remplacé plus tard par un système de matching côté serveur/IA.</p></aside></div>`; }
  function bindProfile() { document.getElementById("profile-form").addEventListener("submit", (event) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); U().saveProfile(form); U().showToast("Profil de veille enregistré."); }); }
  function alertMarkup(alert) { const result = calculateAlertResults(alert); const criteria = [alert.category && `Catégorie : ${alert.category}`, alert.wilaya && `Wilaya : ${alert.wilaya}`, alert.keywords && `Mots-clés : ${alert.keywords}`].filter(Boolean); return `<article class="alert-card card"><div><h2>${U().escapeHTML(alert.name)}</h2><div class="criteria-line">${criteria.map((item) => `<span class="criteria">${U().escapeHTML(item)}</span>`).join("") || '<span class="criteria">Tous les appels d\'offres</span>'}</div></div><div class="alert-result"><strong>${result}</strong><span>résultat${result !== 1 ? "s" : ""} actuel${result !== 1 ? "s" : ""}</span><div class="alert-actions"><button class="btn btn-outline btn-small" data-edit-alert="${alert.id}">Modifier</button><button class="btn btn-danger btn-small" data-delete-alert="${alert.id}">Supprimer</button></div></div></article>`; }
  function alertsMarkup() { return `<div class="app-title-row"><div><h2>Mes alertes</h2><p>Créez vos critères. Dans ce MVP, elles sont conservées localement et ne déclenchent pas encore de notification.</p></div><button id="add-alert" class="btn btn-primary">+ Créer une alerte</button></div><div id="alert-results" class="alert-list"></div>`; }
  function renderAlerts() { const root = document.getElementById("app-page-content"); root.innerHTML = alertsMarkup(); const alerts = getAlerts(); const results = document.getElementById("alert-results"); results.innerHTML = alerts.length ? alerts.map(alertMarkup).join("") : `<div class="empty-state"><div class="empty-icon">◌</div><h2>Aucune alerte créée</h2><p>Créez une alerte par catégorie, wilaya et mots-clés afin de préparer votre veille automatisée.</p><button class="btn btn-primary" data-open-alert>Créer ma première alerte</button></div>`; root.querySelector("#add-alert").addEventListener("click", () => openAlertForm()); root.querySelectorAll("[data-open-alert]").forEach((button) => button.addEventListener("click", () => openAlertForm())); root.querySelectorAll("[data-edit-alert]").forEach((button) => button.addEventListener("click", () => openAlertForm(alerts.find((item) => item.id === button.dataset.editAlert)))); root.querySelectorAll("[data-delete-alert]").forEach((button) => button.addEventListener("click", () => { const remaining = getAlerts().filter((item) => item.id !== button.dataset.deleteAlert); saveAlerts(remaining); U().showToast("Alerte supprimée."); renderAlerts(); })); }
  function openAlertForm(alert) {
    const root = document.getElementById("modal-root"); const item = alert || { id: "", name: "", category: "", wilaya: "", keywords: "" };
    root.innerHTML = `<div class="modal show" role="dialog" aria-modal="true" aria-labelledby="alert-modal-title"><div class="modal-card"><h2 id="alert-modal-title">${alert ? "Modifier l'alerte" : "Créer une alerte"}</h2><p>Les notifications e-mail, WhatsApp et Telegram seront intégrées dans une future version backend.</p><form id="alert-form" class="form-stack"><input name="id" type="hidden" value="${U().escapeHTML(item.id)}"><div class="form-group"><label for="alert-name">Nom de l'alerte</label><input id="alert-name" name="name" required value="${U().escapeHTML(item.name)}" placeholder="Ex. Appels informatique Alger"></div><div class="form-group"><label for="alert-category">Catégorie</label><select id="alert-category" name="category"><option value="">Toutes les catégories</option>${TDZData.categories.map((value) => `<option ${item.category === value ? "selected" : ""}>${U().escapeHTML(value)}</option>`).join("")}</select></div><div class="form-group"><label for="alert-wilaya">Wilaya</label><select id="alert-wilaya" name="wilaya"><option value="">Toutes les wilayas</option>${TDZData.wilayas.map((value) => `<option ${item.wilaya === value ? "selected" : ""}>${U().escapeHTML(value)}</option>`).join("")}</select></div><div class="form-group"><label for="alert-keywords">Mots-clés</label><input id="alert-keywords" name="keywords" value="${U().escapeHTML(item.keywords)}" placeholder="ordinateur, serveur, réseau"></div><div class="modal-actions"><button class="btn btn-outline" type="button" data-modal-close>Annuler</button><button class="btn btn-primary" type="submit">Enregistrer</button></div></form></div></div>`; document.body.classList.add("modal-open"); const close = () => U().closeModal(); root.querySelector("[data-modal-close]").addEventListener("click", close); root.querySelector(".modal").addEventListener("click", (event) => { if (event.target.classList.contains("modal")) close(); }); root.querySelector("#alert-form").addEventListener("submit", (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const list = getAlerts(); const next = { ...values, id: values.id || `alert-${Date.now()}` }; const index = list.findIndex((value) => value.id === next.id); if (index >= 0) list[index] = next; else list.unshift(next); saveAlerts(list); close(); U().showToast("Alerte enregistrée."); renderAlerts(); });
  }
  function subscriptionMarkup() { return `<div class="app-title-row"><div><h2>Mon abonnement</h2><p>Gérez votre plan de veille et découvrez les fonctionnalités à venir.</p></div></div><section class="panel" style="max-width:620px"><p class="plan-label">PLAN ACTUEL</p><h2 style="margin:7px 0;color:var(--navy);font-size:23px">FREE</h2><p style="color:var(--muted);font-size:13px">Accès de démonstration avec recherche et exploration des appels d'offres.</p><ul style="padding-left:18px;color:#526477;font-size:13px;line-height:1.85"><li>Consultation des appels publiés</li><li>Recherche et filtres</li><li>Favoris locaux</li></ul><button class="btn btn-primary" data-pricing-modal>Passer à PRO</button><p class="form-note" style="margin:18px 0 0">Les paiements ne sont pas actifs dans ce prototype frontend.</p></section>`; }
  function render(page) { const root = document.getElementById("app-page-content"); if (!root) return; if (page === "dashboard") root.innerHTML = dashboardMarkup(); else if (page === "favorites") renderFavorites(); else if (page === "profile") { root.innerHTML = profileMarkup(); bindProfile(); } else if (page === "alerts") renderAlerts(); else if (page === "subscription") root.innerHTML = subscriptionMarkup(); }
  window.TDZDashboard = { render, getAlerts, calculateAlertResults, renderAlerts, dashboardMarkup };
})();
