/* Données locales fictives pour la V1. Remplaçables par un adaptateur API. */
const DEMO_DATA = {
  isDemo: true,
  services: [
    { id: 'iphone13-screen', name: 'Changement écran iPhone 13', category: 'Téléphones', device: 'iPhone 13', description: 'Remplacement de l’écran complet d’un iPhone 13.', typicalDuration: '45–90 min', factors: ['Qualité de la pièce (originale, OLED compatible ou LCD)', 'État du châssis et de la face avant', 'Garantie proposée par le réparateur'] },
    { id: 'iphone13-battery', name: 'Changement batterie iPhone 13', category: 'Téléphones', device: 'iPhone 13', description: 'Remplacement de la batterie d’un iPhone 13.', typicalDuration: '30–60 min', factors: ['Capacité et qualité de la batterie', 'État des connecteurs', 'Garantie sur la batterie'] },
    { id: 's23-screen', name: 'Changement écran Samsung S23', category: 'Téléphones', device: 'Samsung Galaxy S23', description: 'Remplacement du bloc écran Samsung Galaxy S23.', typicalDuration: '60–120 min', factors: ['Écran avec ou sans châssis', 'Pièce d’origine ou compatible', 'Capteur d’empreinte et étanchéité'] },
    { id: 's22-battery', name: 'Changement batterie Samsung S22', category: 'Téléphones', device: 'Samsung Galaxy S22', description: 'Remplacement de la batterie Samsung S22.', typicalDuration: '45–75 min', factors: ['Qualité de la batterie', 'Colle et joints de fermeture', 'Garantie offerte'] },
    { id: 'iphone11-charge', name: 'Réparation connecteur de charge iPhone 11', category: 'Téléphones', device: 'iPhone 11', description: 'Diagnostic et remplacement du connecteur de charge.', typicalDuration: '60–120 min', factors: ['Connecteur à remplacer ou simple nettoyage', 'État du microphone', 'Complexité du démontage'] },
    { id: 'iphone12-camera', name: 'Changement caméra iPhone 12', category: 'Téléphones', device: 'iPhone 12', description: 'Remplacement du module caméra arrière.', typicalDuration: '45–90 min', factors: ['Module principal ou ultra grand-angle', 'Qualité du module', 'Tests de stabilisation'] },
    { id: 'phone-speaker', name: 'Réparation haut-parleur téléphone', category: 'Téléphones', device: 'Téléphone', description: 'Nettoyage ou remplacement du haut-parleur interne.', typicalDuration: '30–60 min', factors: ['Simple nettoyage ou remplacement', 'Modèle de téléphone', 'État après oxydation'] },
    { id: 'phone-backglass', name: 'Changement vitre arrière téléphone', category: 'Téléphones', device: 'Téléphone', description: 'Remplacement de la vitre arrière d’un téléphone.', typicalDuration: '60–180 min', factors: ['Technique de retrait de la vitre', 'Modèle de téléphone', 'Qualité de la vitre et des joints'] },
    { id: 'phone-unlock', name: 'Déblocage logiciel téléphone', category: 'Téléphones', device: 'Téléphone', description: 'Diagnostic et intervention logicielle sur téléphone.', typicalDuration: '30–90 min', factors: ['Type de blocage', 'Version du logiciel', 'Sauvegarde de données possible'] },
    { id: 'windows11', name: 'Installation Windows 11', category: 'Informatique', device: 'PC', description: 'Installation et configuration de Windows 11 sur ordinateur.', typicalDuration: '60–120 min', factors: ['Licence incluse ou non', 'Sauvegarde des données', 'Pilotes et logiciels essentiels'] },
    { id: 'laptop-cleaning', name: 'Nettoyage PC portable', category: 'Informatique', device: 'PC portable', description: 'Dépoussiérage interne et changement de pâte thermique si nécessaire.', typicalDuration: '45–120 min', factors: ['Démontage du modèle', 'Changement de pâte thermique', 'État des ventilateurs'] },
    { id: 'ssd-upgrade', name: 'Changement SSD PC', category: 'Informatique', device: 'PC', description: 'Installation d’un SSD et transfert ou installation du système.', typicalDuration: '45–120 min', factors: ['Capacité et marque du SSD', 'Clonage des données', 'Installation de Windows incluse'] },
    { id: 'ram-upgrade', name: 'Changement RAM PC', category: 'Informatique', device: 'PC', description: 'Ajout ou remplacement de mémoire RAM.', typicalDuration: '30–60 min', factors: ['Capacité et type de RAM', 'Nombre de barrettes', 'Compatibilité avec l’ordinateur'] },
    { id: 'laptop-screen', name: 'Réparation écran laptop', category: 'Informatique', device: 'PC portable', description: 'Remplacement de dalle ou réparation de l’affichage.', typicalDuration: '60–120 min', factors: ['Taille et résolution de la dalle', 'Dalle tactile ou non', 'Nappe vidéo à remplacer'] },
    { id: 'motherboard', name: 'Réparation carte mère PC', category: 'Informatique', device: 'PC', description: 'Diagnostic et réparation de carte mère.', typicalDuration: '1–5 jours', factors: ['Panne exacte et composants touchés', 'Disponibilité des composants', 'Niveau de micro-soudure requis'] },
    { id: 'pc-diagnostic', name: 'Diagnostic PC', category: 'Informatique', device: 'PC', description: 'Diagnostic d’une panne matérielle ou logicielle.', typicalDuration: '30–90 min', factors: ['Temps de tests requis', 'Panne intermittente', 'Diagnostic déduit ou détaillé'] },
    { id: 'pc-build', name: 'Montage PC', category: 'Informatique', device: 'PC fixe', description: 'Assemblage et configuration initiale d’un PC.', typicalDuration: '2–4 h', factors: ['Nombre de composants', 'Gestion des câbles', 'Installation système et tests'] },
    { id: 'ps5-hdmi', name: 'Réparation HDMI PS5', category: 'Gaming', device: 'PlayStation 5', description: 'Remplacement du port HDMI d’une PS5.', typicalDuration: '1–3 jours', factors: ['État des pistes de la carte', 'Remplacement du port ou réparation plus large', 'Tests vidéo après intervention'] },
    { id: 'controller-repair', name: 'Réparation manette', category: 'Gaming', device: 'Manette console', description: 'Réparation de joystick, bouton ou gâchette.', typicalDuration: '45–120 min', factors: ['Joystick, bouton ou gâchette', 'Pièces nécessaires', 'Calibrage après réparation'] },
    { id: 'printer-repair', name: 'Réparation imprimante', category: 'Autres', device: 'Imprimante', description: 'Diagnostic et réparation d’une imprimante domestique.', typicalDuration: '1–3 jours', factors: ['Modèle et type d’imprimante', 'Pièce à remplacer', 'Nettoyage des têtes ou mécanismes'] }
  ],
  repairers: [
    { id: 'r1', name: 'Tech Repair Alger', wilaya: 'Alger', commune: 'Bab Ezzouar', address: 'Rue des Frères Bouadou, Bab Ezzouar', phone: '0550 000 101', latitude: 36.713, longitude: 3.183 },
    { id: 'r2', name: 'Mobile Care Hydra', wilaya: 'Alger', commune: 'Hydra', address: 'Rue des Oliviers, Hydra', phone: '0550 000 102', latitude: 36.752, longitude: 3.050 },
    { id: 'r3', name: 'FixLab Birkhadem', wilaya: 'Alger', commune: 'Birkhadem', address: 'Cité El Badr, Birkhadem', phone: '0550 000 103', latitude: 36.715, longitude: 3.055 },
    { id: 'r4', name: 'Oran Tech Service', wilaya: 'Oran', commune: 'Oran', address: 'Boulevard de la Soummam, Oran', phone: '0550 000 104', latitude: 35.697, longitude: -0.633 },
    { id: 'r5', name: 'Blida Digital', wilaya: 'Blida', commune: 'Blida', address: 'Rue Emir Abdelkader, Blida', phone: '0550 000 105', latitude: 36.470, longitude: 2.828 },
    { id: 'r6', name: 'Constantine Fix', wilaya: 'Constantine', commune: 'Constantine', address: 'Avenue Aouati Mostefa, Constantine', phone: '0550 000 106', latitude: 36.365, longitude: 6.614 },
    { id: 'r7', name: 'Smart Clinic Kouba', wilaya: 'Alger', commune: 'Kouba', address: 'Route de Bachdjarah, Kouba', phone: '0550 000 107', latitude: 36.718, longitude: 3.090 },
    { id: 'r8', name: 'PC Express Chéraga', wilaya: 'Alger', commune: 'Chéraga', address: 'Route de Dely Brahim, Chéraga', phone: '0550 000 108', latitude: 36.766, longitude: 2.959 },
    { id: 'r9', name: 'Game Console DZ', wilaya: 'Alger', commune: 'El Biar', address: 'Rue des Jardins, El Biar', phone: '0550 000 109', latitude: 36.767, longitude: 3.024 },
    { id: 'r10', name: 'Atelier Numérique Oran', wilaya: 'Oran', commune: 'Bir El Djir', address: 'Hai Sabah, Bir El Djir', phone: '0550 000 110', latitude: 35.720, longitude: -0.545 }
  ],
  observations: []
};

const demoObservation = (id, serviceId, repairerId, price, dateVerified, verificationMethod, notes) => {
  const repairer = DEMO_DATA.repairers.find((item) => item.id === repairerId);
  return { id, serviceId, repairerId, price, wilaya: repairer.wilaya, commune: repairer.commune, dateVerified, verificationMethod, notes };
};

DEMO_DATA.observations = [
  demoObservation('o01','iphone13-screen','r1',20000,'2026-09-09','phone','Écran OLED compatible, pose comprise.'),
  demoObservation('o02','iphone13-screen','r2',24000,'2026-09-09','in_store','Pièce premium avec garantie de 3 mois.'),
  demoObservation('o03','iphone13-screen','r3',18000,'2026-09-08','phone','Compatible, selon disponibilité.'),
  demoObservation('o04','iphone13-screen','r7',21000,'2026-09-08','social_media','Prix annoncé pour écran complet.'),
  demoObservation('o05','iphone13-screen','r8',22000,'2026-09-05','website','Pièce et main-d’œuvre incluses.'),
  demoObservation('o06','iphone13-screen','r4',24000,'2026-08-23','phone','Écran qualité premium.'),
  demoObservation('o07','iphone13-screen','r5',19000,'2026-07-30','in_store','Compatible sans programmation particulière.'),
  demoObservation('o08','iphone13-screen','r6',18000,'2026-06-29','phone','Tarif indicatif, sous réserve du diagnostic.'),
  demoObservation('o09','iphone13-battery','r1',9500,'2026-09-09','phone','Batterie compatible et pose.'),
  demoObservation('o10','iphone13-battery','r2',12000,'2026-09-06','in_store','Garantie 90 jours.'),
  demoObservation('o11','iphone13-battery','r3',10000,'2026-08-31','social_media','Prix promo affiché.'),
  demoObservation('o12','s23-screen','r1',33000,'2026-09-08','phone','Bloc écran compatible.'),
  demoObservation('o13','s23-screen','r2',39000,'2026-09-09','in_store','Écran d’origine annoncé.'),
  demoObservation('o14','s23-screen','r4',35000,'2026-08-29','website','Main-d’œuvre incluse.'),
  demoObservation('o15','s22-battery','r2',10500,'2026-09-08','phone','Batterie et pose.'),
  demoObservation('o16','s22-battery','r5',9000,'2026-09-02','in_store','Batterie compatible.'),
  demoObservation('o17','s22-battery','r6',11000,'2026-08-21','phone','Garantie un mois.'),
  demoObservation('o18','iphone11-charge','r1',8500,'2026-09-09','in_store','Connecteur de charge à remplacer.'),
  demoObservation('o19','iphone11-charge','r3',7000,'2026-09-04','phone','Tarif selon diagnostic.'),
  demoObservation('o20','iphone11-charge','r7',9000,'2026-08-25','social_media','Connecteur et montage.'),
  demoObservation('o21','iphone12-camera','r2',14000,'2026-09-05','phone','Module caméra principal compatible.'),
  demoObservation('o22','iphone12-camera','r1',12500,'2026-08-28','in_store','Test caméra inclus.'),
  demoObservation('o23','phone-speaker','r3',3500,'2026-09-09','phone','Nettoyage ou remplacement simple.'),
  demoObservation('o24','phone-speaker','r5',4500,'2026-09-01','in_store','Pièce selon le modèle.'),
  demoObservation('o25','phone-backglass','r7',7500,'2026-09-06','social_media','Pour téléphone récent, hors châssis.'),
  demoObservation('o26','phone-backglass','r1',9000,'2026-08-24','phone','Selon modèle et couleur.'),
  demoObservation('o27','phone-unlock','r2',4000,'2026-09-08','in_store','Déblocage logiciel standard.'),
  demoObservation('o28','phone-unlock','r6',5000,'2026-08-27','phone','Selon type de verrouillage.'),
  demoObservation('o29','windows11','r8',3500,'2026-09-09','in_store','Installation sans licence.'),
  demoObservation('o30','windows11','r1',4500,'2026-09-07','phone','Pilotes et logiciels essentiels.'),
  demoObservation('o31','windows11','r4',5000,'2026-09-02','website','Sauvegarde non comprise.'),
  demoObservation('o32','laptop-cleaning','r8',4500,'2026-09-08','in_store','Dépoussiérage et pâte thermique.'),
  demoObservation('o33','laptop-cleaning','r5',3500,'2026-09-03','phone','Nettoyage standard.'),
  demoObservation('o34','laptop-cleaning','r10',5000,'2026-08-18','social_media','Selon difficulté de démontage.'),
  demoObservation('o35','ssd-upgrade','r8',11000,'2026-09-09','in_store','SSD 256 Go et installation.'),
  demoObservation('o36','ssd-upgrade','r1',15000,'2026-09-04','phone','SSD 512 Go, système inclus.'),
  demoObservation('o37','ssd-upgrade','r4',13000,'2026-08-26','website','Tarif matériel et pose.'),
  demoObservation('o38','ram-upgrade','r8',6000,'2026-09-05','phone','8 Go DDR4 et pose.'),
  demoObservation('o39','ram-upgrade','r5',7500,'2026-08-31','in_store','16 Go suivant compatibilité.'),
  demoObservation('o40','laptop-screen','r8',14000,'2026-09-07','in_store','Dalle 15,6 pouces standard.'),
  demoObservation('o41','laptop-screen','r4',16500,'2026-08-28','phone','Dalle FHD, main-d’œuvre comprise.'),
  demoObservation('o42','motherboard','r8',18000,'2026-09-01','phone','Après diagnostic, tarif variable.'),
  demoObservation('o43','motherboard','r6',22000,'2026-08-15','in_store','Intervention micro-soudure.'),
  demoObservation('o44','pc-diagnostic','r8',2000,'2026-09-09','in_store','Diagnostic matériel ou logiciel.'),
  demoObservation('o45','pc-diagnostic','r1',2500,'2026-09-03','phone','Déduit si réparation acceptée, selon le cas.'),
  demoObservation('o46','pc-build','r8',7500,'2026-09-06','phone','Montage et tests, sans Windows.'),
  demoObservation('o47','pc-build','r4',9000,'2026-08-20','website','Configuration et câblage complet.'),
  demoObservation('o48','ps5-hdmi','r9',14000,'2026-09-09','in_store','Port HDMI et test vidéo.'),
  demoObservation('o49','ps5-hdmi','r1',16000,'2026-09-02','phone','Selon l’état des pistes.'),
  demoObservation('o50','ps5-hdmi','r4',15000,'2026-08-26','social_media','Réparation port HDMI annoncée.'),
  demoObservation('o51','controller-repair','r9',5000,'2026-09-08','in_store','Remplacement joystick pour drift.'),
  demoObservation('o52','controller-repair','r10',4500,'2026-08-29','phone','Pièce et calibrage inclus.'),
  demoObservation('o53','printer-repair','r8',6000,'2026-09-04','phone','Diagnostic inclus dans la réparation.'),
  demoObservation('o54','printer-repair','r5',7500,'2026-08-19','in_store','Selon modèle et pièce nécessaire.')
];
